/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package CapaPresentacion;

/**
 *
 * @author Casa
 */
public class VistaConfiguracion extends javax.swing.JDialog {

    /**
     * Creates new form VistaConf
     */
    private boolean aceptar;
    public VistaConfiguracion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public void setIdioma(String idioma){
        textIdioma.setText(idioma);
    }
    
    public void setRuta(String ruta){
        textRuta.setText(ruta);
    }
    
    public void setBaseSize(int base){        
        textBaseSize.setText(Integer.toString(base));
    }
    
    public void setRecreate(double index){        
        textRecreate.setText(Integer.toString((int)index));      
    }
    
    public String getIdioma(){
        return textIdioma.getText();
    }
    
    public String getRuta(){
        return textRuta.getText();
    }
    
    public String getBaseSize(){        
        return textBaseSize.getText();
    }
    
    public String getRecreate(){        
        return textRecreate.getText();      
    }
    
    public boolean getAceptar(){
        return aceptar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonAceptar = new javax.swing.JButton();
        textBaseSize = new javax.swing.JTextField();
        textRuta = new javax.swing.JTextField();
        textIdioma = new javax.swing.JTextField();
        textRecreate = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        buttonCancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonAceptar.setText("Aceptar");
        buttonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 279, 122, 37));

        textBaseSize.setText("jTextField1");
        getContentPane().add(textBaseSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 145, 169, -1));

        textRuta.setText("jTextField1");
        getContentPane().add(textRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 71, 169, -1));

        textIdioma.setText("jTextField1");
        getContentPane().add(textIdioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 105, 169, -1));

        textRecreate.setText("jTextField1");
        getContentPane().add(textRecreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 169, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Ruta Articulos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 71, 247, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Idioma");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 105, 271, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Tamaño Base EV");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 145, 126, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Indice Base Refresh (%)");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 183, -1, -1));

        buttonCancelar.setText("Cancelar");
        buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 279, 122, 37));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Para que los cambios tengan efecto, debe reiniciar la aplicación");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 232, -1, 29));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Modificar Configuración");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 22, 340, -1));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAceptarActionPerformed
        aceptar = true;
        dispose();
    }//GEN-LAST:event_buttonAceptarActionPerformed

    private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_buttonCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAceptar;
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField textBaseSize;
    private javax.swing.JTextField textIdioma;
    private javax.swing.JTextField textRecreate;
    private javax.swing.JTextField textRuta;
    // End of variables declaration//GEN-END:variables
}
